name: Enforce PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, edited]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Require at least one review approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedReviews = reviews.filter(r => r.state === 'APPROVED');
            if (approvedReviews.length < 1) {
              core.setFailed("This pull request must be approved by at least one reviewer.");
            }
